language: java
jdk:
  - oraclejdk8
script:
- echo "Compiling and packaging Cloud Explorer....."
- ant
- cp $HOME/build/rusher81572/cloudExplorer/src/cloudExplorer/Release_Notes.txt $HOME/build/rusher81572/cloudExplorer/dist/
- mkdir $HOME/build/rusher81572/cloudExplorer/cloudExplorer
- cp -rf dist/* cloudExplorer
- zip --exclude=*.git* -r cloudExplorer-$VERSION.zip cloudExplorer
- echo "Starting functional testing......"
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar listbuckets
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar makebucket testing81572
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar build cloudExplorer-$VERSION.zip $HOME/build/rusher81572/cloudExplorer/cloudExplorer-$VERSION.zip cloudexplorer
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar createfolder testing81572 synctest
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar synctos3 $HOME/build/rusher81572/cloudExplorer/src testing81572 synctest
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar ls testing81572
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar syncfroms3 /tmp testing81572 synctest
- ls /tmp/synctest/src/cloudExplorer
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar search testing81572 png
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar deleteall testing81572
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar uploadtest testing81572 10 10 10 mixed
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar download testing81572 10 10 10 mixed
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar deleteall testing81572
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar rmbucket testing81572
- echo "Starting upgrade testing....."
- sed -i 's/major = \"8\"/major = \"7\"/'  $HOME/build/rusher81572/cloudExplorer/src/cloudExplorer/NewJFrame.java
- sed -i 's/minor = \"0\"/minor = \"00\"/'  $HOME/build/rusher81572/cloudExplorer/src/cloudExplorer/NewJFrame.java
- ant
- rm -rf cloudExplorer
- mkdir $HOME/build/rusher81572/cloudExplorer/cloudExplorer
- cp -rf dist/* cloudExplorer
- java -jar $HOME/build/rusher81572/cloudExplorer/cloudExplorer/CloudExplorer.jar upgrade
- java -jar $HOME/build/rusher81572/cloudExplorer/cloudExplorer/CloudExplorer.jar help
- ls -al $HOME/build/rusher81572/cloudExplorer/cloudExplorer/lib
