language: java
jdk:
  - oraclejdk8
script:
- ant
- mkdir $HOME/build/rusher81572/cloudExplorer/cloudExplorer
- cp -rf dist/* cloudExplorer
- zip --exclude=*.git* -r cloudExplorer.zip cloudExplorer
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar put $HOME/build/rusher81572/cloudExplorer.zip cloudexplorer
- java -jar listbuckets
